title: Philipp Haller

author: Philipp Haller
work-address: 'EPFL Science Park (PSED) <br/>1015 Lausanne, Switzerland'
email-address: 'philipp.haller@typesafe.com'
phone-number: '+41 76 205 39 32'
twitter: philippkhaller

# destination: ../testdir
# baseurl: ../testdir